use news_ag::{
    AbcNews, AlJazeera, AlMonitor, AmericanConservative, AmericanProspect, Alternet,
    ApNews, ArabNews, ArsTechnica, AtlantaJournalConstitution, Atlantic, Axios, BaltimoreSun,
    BangkokPost, BangkokPostBusiness, BangkokPostWorld, BbcNews, BalkanInsight, BelfastTelegraph,
    Benzinga, Billboard, Bloomberg, BostonGlobe, BusinessInsider, CalgaryHerald, CbsNews,
    CharlestonGazette, CharlestonGazetteMail, CharlestonPostAndCourier, ChicagoTribune,
    ChristianScienceMonitor, CincinnatiEnquirer, Clarin, ClevelandPlainDealer, Cnbc, Cnet, Cnn,
    ColumbusDispatch, CommonDreams, Conversation, CorriereDellaSera, CyprusMail, DailyBeast,
    DailyCaller, DailyKos, DailyMail, DailyTelegraph, DailyWire, DallasMorningNews,
    DemocracyNow, DenverPost, DerSpiegel, DetroitFreePress, DeutscheWelle, DropSiteNews,
    Economist, EdmontonJournal, ElPais, Empire, Engadget, Eurasianet, Euronews, Express,
    FastCompany, FinancialTimes, FolhaDeSPaulo, Forbes, ForeignPolicy, Fortune, FoxNews,
    France24, FranceInfo, FrankfurterAllgemeineZeitung, GameSpot, Gizmodo, GlobalNews,
    GlobalVoices, GlobeAndMail, Guardian, Haaretz, HalifaxChronicleHerald,
    HartfordCourant, HeraldScotland, HoustonChronicle, HuffingtonPost, Ign,
    Independent, IndependentUK, IndianapolisStar, InterceptFirstLook, InvestorsBusinessDaily,
    IrishTimes, Jacobin, JapanTimes, JerusalemPost, Kiplinger, Kotaku,
    KyivIndependent, LaPresse, LaRepubblica, LeMonde, LosAngelesTimes,
    LouisvilleCourierJournal, MarketWatch, Mashable, MilitaryTimes,
    MiddleEastEye, MinneapolisStarTribune, MirrorUK, MontrealGazette, MoscowTimes, MotherJones,
    Msnbc, NerdWallet, NashvilleTennessean, Nation, NationalPost, NationalReview, Nature,
    NbcNews, NewRepublic, NewScientist, NewStatesman, NewYorkPost, NewYorkTimes, NewYorker,
    Newsweek, NHKWorld, NikkeiAsia, NikkeiEnglish, Nme, Npr, OklahomaCityOklahoman,
    Oregonian, OrlandoSentinel, OttawaCitizen, Pcmag, PhiladelphiaInquirer, Pitchfork,
    PittsburghPostGazette, Politico, Polygon, ProPublica, ProvidenceJournal, Quartz, RFI,
    RawStory, Reason, ReginaLeaderPost, Reuters, RichmondTimesDispatch, RollingStone,
    SaskatoonStarPhoenix, Salon, ScienceMagazine, ScientificAmerican, Scotsman, ScreenRant,
    SeattleTimes, Slashdot, SkyNews, SouthChinaMorningPost, Spectator, StJohnsTelegram,
    StLouisPostDispatch, StarLedger, StraitsTimes, SydneyMorningHerald, TampaBayTimes,
    TechCrunch, Techdirt, Techmeme, Telegraph, TelegraphUK, TheAge, TheArtNewspaper,
    TheAustralian, TheBlaze, TheBulwark, TheHill, TheHindu,
    TheHollywoodReporter, TheIntercept, TheMirror, TheSun, TheTimes, TheVerge,
    TexasTribune, Time, TimesOfIndia, TomsGuide, TorontoStar, Truthout,
    UnitedPressInternational, UsaToday, VancouverSun, Variety, VentureBeat,
    ViceNews, Vox, WallStreetJournal, WashingtonPost, Wgn, WinnipegFreePress, Wired,
    YoungTurks, Zeteo, source::Source,
};

/// Macro-driven helper: assert a source reports the exact expected display name.
fn assert_has_name<S: Source>(expected_name: &str) {
    let name = S::name();
    assert_eq!(
        name, expected_name,
        "source {expected_name:?} reported unexpected name {name:?}"
    );
}

macro_rules! require_names {
    ( $($source:ty as $label:literal),+ $(,)? ) => {
        $(
            assert_has_name::<$source>($label);
        )+
    };
}

#[test]
fn every_source_reports_a_name() {
    require_names!(
    AbcNews as "ABC News", AlJazeera as "Al Jazeera", AlMonitor as "Al-Monitor",
        AmericanConservative as "The American Conservative",
        AmericanProspect as "The American Prospect", ApNews as "AP News",
        ArsTechnica as "Ars Technica",
        AtlantaJournalConstitution as "The Atlanta Journal-Constitution",
        Atlantic as "The Atlantic", Axios as "Axios", BaltimoreSun as "The Baltimore Sun",
        BangkokPost as "The Bangkok Post", BbcNews as "BBC News",
        BelfastTelegraph as "The Belfast Telegraph", Billboard as "Billboard",
        Bloomberg as "Bloomberg", BostonGlobe as "The Boston Globe",
        BusinessInsider as "Business Insider", CalgaryHerald as "The Calgary Herald",
        CbsNews as "CBS News", CharlestonGazette as "The Charleston Gazette",
        CharlestonGazetteMail as "The Charleston Gazette-Mail",
        CharlestonPostAndCourier as "The Charleston Post and Courier",
        ChicagoTribune as "The Chicago Tribune",
        ChristianScienceMonitor as "The Christian Science Monitor",
        CincinnatiEnquirer as "The Cincinnati Enquirer", Clarin as "Clarín",
        ClevelandPlainDealer as "The Cleveland Plain Dealer", Cnbc as "CNBC", Cnet as "CNET",
        Cnn as "CNN", ColumbusDispatch as "The Columbus Dispatch", CommonDreams as "Common Dreams",
        CorriereDellaSera as "Corriere della Sera", DailyBeast as "The Daily Beast",
        DailyCaller as "The Daily Caller", DailyKos as "The Daily Kos",
        DailyMail as "The Daily Mail", DailyTelegraph as "The Daily Telegraph",
        DailyWire as "The Daily Wire", DallasMorningNews as "The Dallas Morning News",
        DemocracyNow as "Democracy Now!", DenverPost as "The Denver Post",
        DerSpiegel as "Der Spiegel", DetroitFreePress as "The Detroit Free Press",
        DeutscheWelle as "Deutsche Welle", DropSiteNews as "Drop Site News",
        Economist as "The Economist", EdmontonJournal as "The Edmonton Journal",
        ElPais as "El País", Empire as "Empire", Engadget as "Engadget", Euronews as "Euronews",
        Express as "The Express", FastCompany as "Fast Company",
        FinancialTimes as "Financial Times", FolhaDeSPaulo as "Folha de S.Paulo",
        Forbes as "Forbes", ForeignPolicy as "Foreign Policy", Fortune as "Fortune",
        FoxNews as "Fox News", France24 as "France 24",
        FrankfurterAllgemeineZeitung as "Frankfurter Allgemeine Zeitung", GameSpot as "GameSpot",
        Gizmodo as "Gizmodo", GlobalNews as "Global News", GlobeAndMail as "The Globe and Mail",
        Guardian as "The Guardian", Haaretz as "Haaretz",
        HalifaxChronicleHerald as "The Halifax Chronicle Herald",
        HartfordCourant as "The Hartford Courant", HeraldScotland as "The Herald",
        HoustonChronicle as "The Houston Chronicle", HuffingtonPost as "The Huffington Post",
        Ign as "IGN", Independent as "The Independent",
        IndianapolisStar as "The Indianapolis Star", IrishTimes as "The Irish Times",
        Jacobin as "Jacobin", JapanTimes as "The Japan Times",
        JerusalemPost as "The Jerusalem Post", Kiplinger as "Kiplinger", Kotaku as "Kotaku",
        KyivIndependent as "The Kyiv Independent", LaPresse as "La Presse",
        LaRepubblica as "La Repubblica", LeMonde as "Le Monde",
        LosAngelesTimes as "The Los Angeles Times",
        LouisvilleCourierJournal as "The Louisville Courier-Journal", MarketWatch as "MarketWatch",
        Mashable as "Mashable", MiddleEastEye as "Middle East Eye",
        MinneapolisStarTribune as "The Minneapolis Star Tribune",
        MontrealGazette as "The Montreal Gazette", MoscowTimes as "The Moscow Times",
        MotherJones as "Mother Jones", Msnbc as "MSNBC",
        NashvilleTennessean as "The Nashville Tennessean", Nation as "The Nation",
        NationalPost as "The National Post", NationalReview as "National Review",
        Nature as "Nature", NbcNews as "NBC News", NewRepublic as "The New Republic",
        NewScientist as "New Scientist", NewStatesman as "The New Statesman",
        NewYorkPost as "The New York Post", NewYorkTimes as "New York Times",
        NewYorker as "The New Yorker", Newsweek as "Newsweek", NikkeiAsia as "Nikkei Asia",
        Nme as "NME", Npr as "NPR", OklahomaCityOklahoman as "The Oklahoma City Oklahoman",
        Oregonian as "The Oregonian", OrlandoSentinel as "The Orlando Sentinel",
        OttawaCitizen as "The Ottawa Citizen", Pcmag as "PCMag",
        PhiladelphiaInquirer as "The Philadelphia Inquirer", Pitchfork as "Pitchfork",
        PittsburghPostGazette as "The Pittsburgh Post-Gazette", Politico as "Politico",
        Polygon as "Polygon", ProPublica as "ProPublica",
        ProvidenceJournal as "The Providence Journal", Quartz as "Quartz", Reason as "Reason",
        ReginaLeaderPost as "The Regina Leader-Post", Reuters as "Reuters",
        RichmondTimesDispatch as "The Richmond Times-Dispatch", RollingStone as "Rolling Stone",
        SaskatoonStarPhoenix as "The Saskatoon StarPhoenix", ScienceMagazine as "Science Magazine",
        ScientificAmerican as "Scientific American", Scotsman as "The Scotsman",
        ScreenRant as "Screen Rant", SeattleTimes as "The Seattle Times", SkyNews as "Sky News",
        SouthChinaMorningPost as "South China Morning Post", Spectator as "The Spectator",
        StJohnsTelegram as "The St. John's Telegram",
        StLouisPostDispatch as "The St. Louis Post-Dispatch", StarLedger as "The Star-Ledger",
        StraitsTimes as "The Straits Times", SydneyMorningHerald as "The Sydney Morning Herald",
        TampaBayTimes as "The Tampa Bay Times", TechCrunch as "TechCrunch",
        Telegraph as "The Telegraph", TheAge as "The Age", TheArtNewspaper as "The Art Newspaper",
        TheAustralian as "The Australian", TheBlaze as "The Blaze", TheBulwark as "The Bulwark",
        TheHill as "The Hill", TheHindu as "The Hindu",
        TheHollywoodReporter as "The Hollywood Reporter", TheIntercept as "The Intercept",
        TheMirror as "The Mirror", TheSun as "The Sun", TheTimes as "The Times",
        TheVerge as "The Verge", Time as "Time", TimesOfIndia as "The Times of India",
        TorontoStar as "The Toronto Star",
        UnitedPressInternational as "United Press International", UsaToday as "USA Today",
        VancouverSun as "The Vancouver Sun", Variety as "Variety", VentureBeat as "VentureBeat",
        ViceNews as "Vice News", Vox as "Vox", WallStreetJournal as "The Wall Street Journal",
        WashingtonPost as "The Washington Post", Wgn as "WGN",
        WinnipegFreePress as "The Winnipeg Free Press", Wired as "Wired",
        YoungTurks as "The Young Turks", Zeteo as "Zeteo",
        Alternet as "Alternet", ArabNews as "Arab News",
        BangkokPostBusiness as "Bangkok Post - Business",
        BangkokPostWorld as "Bangkok Post - World", BalkanInsight as "Balkan Insight",
        Benzinga as "Benzinga", CyprusMail as "Cyprus Mail",
        Eurasianet as "Eurasianet", FranceInfo as "France Info",
        GlobalVoices as "Global Voices",
        IndependentUK as "The Independent (UK)",
        InterceptFirstLook as "The Intercept - First Look",
        InvestorsBusinessDaily as "Investor's Business Daily",
        MilitaryTimes as "Military Times", MirrorUK as "The Mirror (UK)",
        NerdWallet as "NerdWallet",
        NHKWorld as "NHK World", NikkeiEnglish as "Nikkei Asia (English)",
        RFI as "Radio France Internationale", RawStory as "Raw Story",
        Salon as "Salon", Slashdot as "Slashdot", Techdirt as "Techdirt",
        Techmeme as "Techmeme", TelegraphUK as "The Telegraph (UK)",
        Conversation as "The Conversation",
        TexasTribune as "The Texas Tribune",
        TomsGuide as "Tom's Guide",
        Truthout as "Truthout",
    );
}
